package controllers.enums;

public enum DynamicListType {
    EMPTY,
    BUILDINGS_LIST,
    CONSTRUCTION_STATUS_LIST,
    TROOPS_LIST,
    TRAINING_STATUS_LIST,
    AVAILABLE_TROOPS_LIST,
    MINE,
    TARGET,
    VILLAGE_MAPS_LIST,
    AVAILABLE_ENEMY_MAPS_LIST;
}
