package controllers.enums;

public enum ModelBasedList {
    BUILDINGS_LIST,
    RESOURCES_LIST,
    CONSTRUCTION_STATUS_LIST,
    AVAILABLE_BUILDINGS_LIST,
    TROOPS_LIST,
    TRAINING_STATUS_LIST,
    AVAILABLE_TROOPS_LIST,
    MINE,
    TARGET,
    AVAILABLE_MAPS_LIST,
}
