package controllers.enums;

public enum ModelBasedList {
    BUILDINGS_LIST,
    RESOURCES_LIST,
    UNDER_CONSTRUCTION_LIST,
    CONSTRUCTABLE_LIST,
    TROOPS_LIST,
    TRAINING_TROOPS_LIST,
    AVAILABLE_TROOPS_LIST,
    MINE,
    TARGET,
    AVAILABLE_MAPS_LIST,
}
